/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell4
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    Connection          con     = null;
    PreparedStatement   ps      = null;
    ResultSet           rs      = null;
    String query;
    List<RoomDataPOJO> roomDataList;
    DbManager db;
    
    public Account() {
        roomDataList = new ArrayList();
        db = new DbManager();
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            query = "SELECT * FROM RoomsData";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();
            
            while(rs.next())
            {
                roomDataList.add(new RoomDataPOJO(rs.getInt("ID"), rs.getString("Room Type"), rs.getInt("Total Rooms"), rs.getInt("Available")));
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        checkReservationbtn = new javax.swing.JButton();
        editReservationbtn = new javax.swing.JButton();
        checkOutbtn = new javax.swing.JButton();
        servicesBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel1.setLayout(null);

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(20, 500, 55, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 0, 100, 130);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Serena Hotel");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 330, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 130);

        jPanel3.setLayout(null);

        checkReservationbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkReservationbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        checkReservationbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkReservationbtn.setText("Check Reservation");
        checkReservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkReservationbtnActionPerformed(evt);
            }
        });
        jPanel3.add(checkReservationbtn);
        checkReservationbtn.setBounds(90, 100, 150, 30);

        editReservationbtn.setBackground(new java.awt.Color(0, 0, 0));
        editReservationbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        editReservationbtn.setForeground(new java.awt.Color(255, 255, 255));
        editReservationbtn.setText("Edit Reservation");
        editReservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editReservationbtnActionPerformed(evt);
            }
        });
        jPanel3.add(editReservationbtn);
        editReservationbtn.setBounds(90, 140, 150, 30);

        checkOutbtn.setBackground(new java.awt.Color(0, 0, 0));
        checkOutbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        checkOutbtn.setForeground(new java.awt.Color(255, 255, 255));
        checkOutbtn.setText("Checkout");
        checkOutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutbtnActionPerformed(evt);
            }
        });
        jPanel3.add(checkOutbtn);
        checkOutbtn.setBounds(90, 180, 150, 30);

        servicesBtn.setBackground(new java.awt.Color(0, 0, 0));
        servicesBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        servicesBtn.setForeground(new java.awt.Color(255, 255, 255));
        servicesBtn.setText("Avail Services");
        servicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesBtnActionPerformed(evt);
            }
        });
        jPanel3.add(servicesBtn);
        servicesBtn.setBounds(90, 60, 150, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\hotel-serena-10.jpg")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 330, 260);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(140, 180, 330, 260);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("User Main");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(230, 140, 150, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        Reception rec = new Reception ();
        rec.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkReservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkReservationbtnActionPerformed
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            String email = JOptionPane.showInputDialog(null, "Please Enter you Email").trim().toLowerCase();
            query = "select * from UserPData where Email = ?";
            ps = con.prepareStatement(query);
            ps.setString(1,email);
            rs = ps.executeQuery();
            
            int id=0;
            int count = 0;
            
            while(rs.next())
            {
                id = rs.getInt("ID");
                count=count+1;
            }
            if (count == 1)
            {
                query = "select * from UserRData where ID = ?";
                ps = con.prepareStatement(query);
                ps.setInt(1,id);
                rs = ps.executeQuery();
                
                String checkin = null;
                String checkout = null;
                
                while(rs.next())
                {
                    checkin  = rs.getString("Checkin");
                    checkout = rs.getString("Checkout");
                }
                JOptionPane.showMessageDialog(null,"Checkin Information: "+checkin+"\nExpected Checkout: "+checkout);
            }
            else if (count > 1)
            {
                JOptionPane.showMessageDialog(null, "Duplicate User found, Access Deined!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Entry!");                
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_checkReservationbtnActionPerformed

    private void editReservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editReservationbtnActionPerformed
        this.setVisible(false);
        EditReservation er = new EditReservation();
        er.setVisible(true);
    }//GEN-LAST:event_editReservationbtnActionPerformed

    private void checkOutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutbtnActionPerformed
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            String email = JOptionPane.showInputDialog(null, "Please Enter you Email").trim().toLowerCase();
            query = "select * from UserPData where Email = ?";
            ps = con.prepareStatement(query);
            ps.setString(1,email);
            rs = ps.executeQuery();
                        
            int id=0;
            int count = 0;
            
            while(rs.next())
            {
                id = rs.getInt("ID");
                count=count+1;
            }
            
            if (count == 1)
            {  
                try
                {
                    query = "select * from Bill where ID = ?";
                    ps = con.prepareStatement(query);
                    ps.setInt(1,id);
                    rs = ps.executeQuery();
                    int food        = 0;
                    int beverages   = 0;
                    int laundary    = 0;
                    while(rs.next())
                    {
                        food        = rs.getInt("Food");
                        beverages   = rs.getInt("Beverages");
                        laundary    = rs.getInt("Laundary");
                    }
                    
                    query = "select * from UserRData where ID = ?";
                    ps = con.prepareStatement(query);
                    ps.setInt(1,id);
                    rs = ps.executeQuery();
                    String checkin  = null;
                    String checkout = null;
                    String roomType = null;
                    int    rooms    = 0;
                    int    stay     = 0;
                    while(rs.next())
                    {
                        checkin     = rs.getString("Checkin");
                        checkout    = rs.getString("Checkout");
                        roomType    = rs.getString("Room Type");
                        rooms       = rs.getInt("No of Rooms");
                        stay        = rs.getInt("No of Days");
                    }
                    
                    int roomBill = 0;
                    if(roomType.equals("Deluxe Room"))
                    {
                        roomBill = rooms*stay*289;
                    }
                    if(roomType.equals("Executive Room"))
                    {
                        roomBill = rooms*stay*325;
                    }
                    if(roomType.equals("Junior Suite"))
                    {
                        roomBill = rooms*stay*375;
                    }
                    if(roomType.equals("Executive Suite"))
                    {
                        roomBill = rooms*stay*498;
                    }
                    if(roomType.equals("Presidential Suite"))
                    {
                        roomBill = rooms*stay*2495;
                    }

                    int total = food + beverages + laundary + roomBill;
                    JOptionPane.showMessageDialog(null, "*****Thank You for staying at Senera Hotel*****\n\n***Receipt***\n\nFood: $"+food+"\nBeverages: $"+beverages+"\nLaundary: $"+laundary+"\nRooms: $"+roomBill+"\n\n______________________\n\nTotal Bill: $"+total);
                    
                    query = "INSERT INTO AdminData ([Checkout],[Transactions]) VALUES (?,?)";
                    ps = con.prepareStatement(query);
                    ps.setString(1, checkout);
                    ps.setInt(2,total);
                    int results = ps.executeUpdate();
                    
                    int deluxeRoom  =  roomDataList.get(0).getAvailRooms();
                    int exeRoom     =  roomDataList.get(1).getAvailRooms();
                    int jSuite      =  roomDataList.get(2).getAvailRooms();
                    int exeSuite    =  roomDataList.get(3).getAvailRooms();
                    int pSuite      =  roomDataList.get(4).getAvailRooms();
                    
                    if(roomType.equals("Deluxe Room"))
                    {
                        deluxeRoom += rooms;
                        db.updataRoom(1, deluxeRoom);
                    }
                    else if(roomType.equals("Executive Room") )
                    {
                        exeRoom += rooms;
                        db.updataRoom(2, exeRoom);
                    }
                    else if(roomType.equals("Juinor Suite") )
                    {
                        jSuite += rooms;
                        db.updataRoom(3, jSuite);
                    }
                    else if(roomType.equals("Executive Suite") )
                    {
                        exeSuite += rooms;
                        db.updataRoom(4, exeSuite);
                    }
                    else
                    {
                        pSuite += rooms;
                        db.updataRoom(5, pSuite);
                    }
                    DeleteData d = new DeleteData(id);
                    d.Delete();
                }
                catch (SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                }
            }
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(Account.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }//GEN-LAST:event_checkOutbtnActionPerformed

    private void servicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesBtnActionPerformed
        this.setVisible(false);
        Services s = new Services();
        s.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_servicesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton checkOutbtn;
    private javax.swing.JButton checkReservationbtn;
    private javax.swing.JButton editReservationbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton servicesBtn;
    // End of variables declaration//GEN-END:variables
}
