/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell4
 */
public class AddGuest extends javax.swing.JFrame {

    /**
     * Creates new form AddGuest
     */
    public AddGuest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nameBtn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        contactBtn = new javax.swing.JTextField();
        emailBtn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cnicBtn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        nextBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(20, 500, 55, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 0, 100, 130);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Serena Hotel");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 330, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 130);

        jPanel2.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(8, 56, 40, 20);

        nameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nameBtn);
        nameBtn.setBounds(90, 50, 186, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact no.:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 110, 76, 17);

        contactBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBtnActionPerformed(evt);
            }
        });
        jPanel2.add(contactBtn);
        contactBtn.setBounds(90, 100, 186, 30);

        emailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBtnActionPerformed(evt);
            }
        });
        jPanel2.add(emailBtn);
        emailBtn.setBounds(90, 150, 186, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 160, 45, 17);

        cnicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cnicBtn);
        cnicBtn.setBounds(90, 200, 186, 30);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CNIC:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 210, 40, 10);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gender:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 250, 50, 17);

        maleBtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(maleBtn);
        maleBtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        maleBtn.setForeground(new java.awt.Color(255, 255, 255));
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });
        jPanel2.add(maleBtn);
        maleBtn.setBounds(90, 250, 51, 21);

        femaleBtn.setBackground(new Color(0,0,0,0));
        buttonGroup1.add(femaleBtn);
        femaleBtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        femaleBtn.setForeground(new java.awt.Color(255, 255, 255));
        femaleBtn.setText("Female");
        femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleBtnActionPerformed(evt);
            }
        });
        jPanel2.add(femaleBtn);
        femaleBtn.setBounds(220, 250, 63, 21);

        nextBtn.setBackground(new java.awt.Color(0, 0, 0));
        nextBtn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nextBtn);
        nextBtn.setBounds(220, 280, 57, 21);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Personal Information");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(70, 10, 167, 33);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\IMG_0470.JPG")); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 0, 290, 310);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 150, 290, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        String query;
        if (nameBtn.getText().equals("") && contactBtn.getText().equals("") && emailBtn.getText().equals("") && cnicBtn.getText().equals(""))
        {
            nextBtn.setEnabled(false);
        }
        else
        {
            Connection con          = null;
            PreparedStatement ps    = null;
            ResultSet rs            = null;
            try{
                Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
                con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
                
                String n        = nameBtn.getText();
                String num      = (String) contactBtn.getText();
                String email    = emailBtn.getText();
                String cnic     = (String) cnicBtn.getText();
                String gender;
                if (maleBtn.isSelected())
                {
                    gender = "Male";
                }
                else
                {
                    gender = "Female";
                }
                
                String alphanum = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"+"0123456789"+"abcsdefghijklmnopqrstuvwxyz"+"!@#$%^&*";
                StringBuilder sb = new StringBuilder();

                for (int i = 0; i < 8; i++)
                {
                    int index = (int)(alphanum.length()*Math.random());
                    sb.append(alphanum.charAt(index));
                }
                String pass = String.valueOf(sb);
                query = "INSERT INTO UserPData ([Name],[Contact],[Email],[CNIC],[Gender]) VALUES (?,?,?,?,?)";
                ps = con.prepareStatement(query);
                ps.setString(1,n);
                ps.setString(2,num);
                ps.setString(3,email);
                ps.setString(4,cnic);
                ps.setString(5,gender);
                int result = ps.executeUpdate();
                
                upDateIDdata(email, pass);
  
                JOptionPane.showMessageDialog(null, "Please save your password: "+pass,"Booking Information", JOptionPane.INFORMATION_MESSAGE);
                
                Customers c     = new Customers(n,num,email,cnic,gender,pass);
                this.setVisible(false);
                Reservation res = new Reservation ();
                res.setVisible(true);        
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_nextBtnActionPerformed

    private void upDateIDdata(String email, String pass)
    {
        Connection con          = null;
        PreparedStatement ps    = null;
        ResultSet rs            = null;
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            String query = "INSERT INTO UserLogin ([Email],[Password]) VALUES (?,?)";
            ps = con.prepareStatement(query);
            ps.setString(1,email);
            ps.setString(2,pass);
            int result = ps.executeUpdate();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                
    }
    private void femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleBtnActionPerformed

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    private void cnicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicBtnActionPerformed

    private void emailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBtnActionPerformed

    private void contactBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactBtnActionPerformed

    private void nameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        Reception rec = new Reception ();
        rec.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddGuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddGuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cnicBtn;
    private javax.swing.JTextField contactBtn;
    private javax.swing.JTextField emailBtn;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JTextField nameBtn;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
