/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell4
 */
public class EditReservation extends javax.swing.JFrame {

    /**
     * Creates new form EditRservation
     */
    Connection          con     = null;
    PreparedStatement   ps      = null;
    ResultSet           rs      = null;
    String Email;
    String query;
    int ID;
    public EditReservation() {
        Email = JOptionPane.showInputDialog(null,"Enter your Email: ").trim().toLowerCase();
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            query = "select * from UserPData where Email = ?";
            ps = con.prepareStatement(query);
            ps.setString(1,Email);
            rs = ps.executeQuery();
            
            int count = 0;
            
            while(rs.next())
            {
                ID = rs.getInt("ID");
                count=count+1;
            }
            if (count == 1)
            {
                initComponents();
                dataTable();
            }
            else if (count > 1)
            {
                JOptionPane.showMessageDialog(null, "Duplicate User found, Access Deined!");
                this.setVisible(false);
                Account acc = new Account ();
                acc.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Entry!");      
                this.setVisible(false);
                Account acc = new Account ();
                acc.setVisible(true);
            }
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void dataTable()
    {
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            query = "select * from UserRData where ID = ?";
            ps = con.prepareStatement(query);
            ps.setInt(1,ID);
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            while(rs.next())
            {
                Object[] row = new Object[3];
                row[0] = rs.getInt("ID");
                row[1] = rs.getString("Checkin");
                row[2] = rs.getString("Checkout");
                model.addRow(row); 
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        updateReservationbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        totalStay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        backBtn.setBackground(new java.awt.Color(0, 0, 0));
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(30, 320, 90, 30);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Checkin", "Checkout"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 340, 44);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edit Reservation");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 60, 130, 30);

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(170, 210, 190, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Stay:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 250, 122, 30);

        updateReservationbtn.setBackground(new java.awt.Color(0, 0, 0));
        updateReservationbtn.setForeground(new java.awt.Color(255, 255, 255));
        updateReservationbtn.setText("Update");
        updateReservationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateReservationbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateReservationbtn);
        updateReservationbtn.setBounds(270, 320, 90, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Checkout:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 210, 122, 30);

        totalStay.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        totalStay.setToolTipText("");
        totalStay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalStayActionPerformed(evt);
            }
        });
        jPanel1.add(totalStay);
        totalStay.setBounds(170, 250, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        Account acc = new Account();
        acc.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateReservationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateReservationbtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        try 
        { 
            String cout = String.valueOf(jDateChooser1.getDate());
            int stay = Integer.parseInt(totalStay.getText());
            System.out.println(stay);
            query = "Update UserRData set Checkout = ? WHERE ID = ?";
            ps = con.prepareStatement(query);
            ps.setString(1, cout);
            //ps.setInt(2, stay);
            ps.setInt(2, ID);
            int doneUpdate = ps.executeUpdate();
            
            query = "Update UserRData set [No of Days] = ? WHERE ID = ?";
            ps = con.prepareStatement(query);
            ps.setInt(1, stay);
            ps.setInt(2, ID);
            int doneUpdate1 = ps.executeUpdate();
            model.removeRow(0);
            dataTable();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_updateReservationbtnActionPerformed

    private void totalStayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalStayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalStayActionPerformed

    /**s
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) 
            {
                if ("Nimbus".equals(info.getName())) 
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) 
        {
            java.util.logging.Logger.getLogger(EditReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField totalStay;
    private javax.swing.JButton updateReservationbtn;
    // End of variables declaration//GEN-END:variables
}
