/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell4
 */
public class Reception extends javax.swing.JFrame {

    /**
     * Creates new form Reception
     */
    List <Customers>    aList;
    String              email; 
    String              password;
    Connection          con     = null;
    PreparedStatement   ps      = null;
    Statement           st      = null;
    ResultSet           rs      = null;
            
    
    public Reception() 
    {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminLoginbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        adminText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        adminPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        userEmailText = new javax.swing.JTextField();
        bookRoomsbtn = new javax.swing.JButton();
        helplinesBtn = new javax.swing.JButton();
        userLoginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 751));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(118, 91, 74));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 751));
        jPanel1.setLayout(null);

        backBtn.setBackground(new java.awt.Color(117, 65, 18));
        backBtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(30, 650, 55, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\Hotels-northern-areas_03.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 270);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Reception");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(440, 280, 160, 50);

        adminLoginbtn.setBackground(new java.awt.Color(117, 65, 18));
        adminLoginbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        adminLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        adminLoginbtn.setText("Login");
        adminLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(adminLoginbtn);
        adminLoginbtn.setBounds(180, 570, 130, 30);

        jLabel3.setBackground(new java.awt.Color(119, 67, 20));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 460, 90, 40);

        adminText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminTextActionPerformed(evt);
            }
        });
        jPanel1.add(adminText);
        adminText.setBounds(180, 470, 130, 30);

        jLabel4.setBackground(new java.awt.Color(119, 67, 20));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 500, 90, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("For Administration");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 410, 210, 40);
        jPanel1.add(adminPassword);
        adminPassword.setBounds(180, 510, 130, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("For Administration");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 410, 210, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("For Guests");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(730, 400, 120, 40);

        jLabel7.setBackground(new java.awt.Color(119, 67, 20));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(670, 450, 90, 40);

        jLabel9.setBackground(new java.awt.Color(119, 67, 20));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 490, 90, 40);
        jPanel1.add(userPassword);
        userPassword.setBounds(760, 500, 130, 30);

        userEmailText.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        userEmailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailTextActionPerformed(evt);
            }
        });
        jPanel1.add(userEmailText);
        userEmailText.setBounds(760, 460, 130, 30);

        bookRoomsbtn.setBackground(new java.awt.Color(117, 65, 18));
        bookRoomsbtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bookRoomsbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookRoomsbtn.setText("Book Rooms");
        bookRoomsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(bookRoomsbtn);
        bookRoomsbtn.setBounds(760, 600, 130, 30);

        helplinesBtn.setBackground(new java.awt.Color(117, 65, 18));
        helplinesBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        helplinesBtn.setForeground(new java.awt.Color(255, 255, 255));
        helplinesBtn.setText("Helplines");
        helplinesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helplinesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(helplinesBtn);
        helplinesBtn.setBounds(900, 320, 100, 25);

        userLoginbtn.setBackground(new java.awt.Color(117, 65, 18));
        userLoginbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        userLoginbtn.setText("Login");
        userLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(userLoginbtn);
        userLoginbtn.setBounds(760, 560, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 751);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginbtnActionPerformed
        String username = adminText.getText().trim();
        String password = String.valueOf(adminPassword.getPassword());
        if (username.equals("admin") && password.equals("0000"))
        {
            this.setVisible(false);
            Admin a = new Admin();
            a.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Wrong Login Information!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_adminLoginbtnActionPerformed

    private void adminTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminTextActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_adminTextActionPerformed

    private void userEmailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailTextActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_userEmailTextActionPerformed

    private void login()
    {
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            String user = userEmailText.getText().trim().toLowerCase();
            char [] pass = userPassword.getPassword();
            String p = String.valueOf(pass);
            
            String query = "select * from UserLogin where Email = ? and Password = ?";
            ps = con.prepareStatement(query);
            ps.setString(1,user);
            ps.setString(2,p);
            rs = ps.executeQuery();
            
            int count = 0;
            while(rs.next())
            {
                count=count+1;
            }
            if (count == 1)
            {
                this.setVisible(false);
                Account acc = new Account();
                acc.setVisible(true);
            }
            else if (count > 1)
            {
                JOptionPane.showMessageDialog(null, "Duplicate User found, Access Deined!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Entry!");                
            }
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private void bookRoomsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomsbtnActionPerformed
        this.setVisible(false);
        AddGuest guest = new AddGuest();
        guest.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bookRoomsbtnActionPerformed

    private void helplinesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helplinesBtnActionPerformed
        JOptionPane.showMessageDialog(null,"Serena Hotel  :  +92 (51) 2874000\nPolice        :  15\nFire Birgade  :  16\nRescure       :  1122\nBomb Disposal :  1332\nAirport       :  +92 (51) 9280960");        // TODO add your handling code here:
    }//GEN-LAST:event_helplinesBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        Main m = new Main ();
        m.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void userLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginbtnActionPerformed
        login();
    }//GEN-LAST:event_userLoginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reception.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reception().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminLoginbtn;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JTextField adminText;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookRoomsbtn;
    private javax.swing.JButton helplinesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField userEmailText;
    private javax.swing.JButton userLoginbtn;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
