/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell4
 */
public class Reservation extends javax.swing.JFrame{

    /**
     * Creates new form Reservation
     */
    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    String query;
    
    List<RoomDataPOJO> roomDataList;
    DbManager db;
    int roomBook;
    public Reservation()
    {
        roomBook =0;
        roomDataList = new ArrayList();
        db = new DbManager();
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            query = "SELECT * FROM RoomsData";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();
            
            while(rs.next()){
                roomDataList.add(new RoomDataPOJO(rs.getInt("ID"), null, -1, rs.getInt("Available")));
            }
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        checkinDC = new com.toedter.calendar.JDateChooser();
        checkoutDC = new com.toedter.calendar.JDateChooser();
        totalStayCB = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        roomTypesCB = new javax.swing.JComboBox<>();
        bookRoomsCB = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 500, 55, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(480, 0, 100, 130);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Serena Hotel");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 10, 330, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 130);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Check out:");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 80, 70, 17);

        bookBtn.setBackground(new java.awt.Color(0, 0, 0));
        bookBtn.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("Book");
        bookBtn.setToolTipText("");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        jPanel3.add(bookBtn);
        bookBtn.setBounds(260, 230, 57, 21);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Reservation Information");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(70, 0, 192, 33);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Check in:");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(10, 40, 70, 17);

        checkinDC.setBackground(new java.awt.Color(255, 255, 255));
        checkinDC.setDate(new java.util.Date(1577309374000L));
        checkinDC.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jPanel3.add(checkinDC);
        checkinDC.setBounds(100, 30, 210, 30);

        checkoutDC.setBackground(new java.awt.Color(255, 255, 255));
        checkoutDC.setFocusTraversalPolicyProvider(true);
        checkoutDC.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jPanel3.add(checkoutDC);
        checkoutDC.setBounds(100, 70, 210, 30);

        totalStayCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        totalStayCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalStayCBActionPerformed(evt);
            }
        });
        jPanel3.add(totalStayCB);
        totalStayCB.setBounds(100, 170, 210, 20);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Total Stay:");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 170, 75, 17);

        roomTypesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe Room", "Executive Room", "Junior Suite", "Executive Suite", "Presidential Suite" }));
        roomTypesCB.setToolTipText("");
        roomTypesCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypesCBActionPerformed(evt);
            }
        });
        jPanel3.add(roomTypesCB);
        roomTypesCB.setBounds(100, 110, 210, 20);

        bookRoomsCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        bookRoomsCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRoomsCBActionPerformed(evt);
            }
        });
        jPanel3.add(bookRoomsCB);
        bookRoomsCB.setBounds(100, 140, 210, 20);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rooms:");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 140, 47, 17);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Type:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(10, 110, 70, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 8)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome drink, Buffet breakfast, Mini-bar, Newspaper, Swimming pool,WiFi");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 190, 310, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("377 sq ft, 2 People,  $298");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(150, 200, 170, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\quetta-serena-hotel.jpg")); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, 0, 330, 260);
        jLabel15.getAccessibleContext().setAccessibleName("jLabel15");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(140, 180, 330, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
       
        int numRooms    = 0;
        int bill        = 0;
        String roomtype = null;
        
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            String cin      = String.valueOf(checkinDC.getDate());
            String cout     = String.valueOf(checkoutDC.getDate());
            int persons     = totalStayCB.getSelectedIndex()+1;
            
            int deluxeRoom  =  roomDataList.get(0).getAvailRooms();
            int exeRoom     =  roomDataList.get(1).getAvailRooms();
            int jSuite      =  roomDataList.get(2).getAvailRooms();
            int exeSuite    =  roomDataList.get(3).getAvailRooms();
            int pSuite      =  roomDataList.get(4).getAvailRooms();
            
            
            if (roomTypesCB.getSelectedIndex()== 0)
            {
                if (deluxeRoom == 0)
                {
                    JOptionPane.showMessageDialog(null,"Sorry! No Deluxe room available.");
                }
                else
                {
                    deluxeRoom -= roomBook;
                    db.updataRoom(1, deluxeRoom);
                    numRooms    = bookRoomsCB.getSelectedIndex()+1;
                    roomtype    = "Deluxe Room";
                }
            }
            else if (roomTypesCB.getSelectedIndex()== 1)
            {
                if (exeRoom == 0)
                {
                    JOptionPane.showMessageDialog(null,"Sorry! No Executive room available.");
                }
                else
                {
                    exeRoom -= roomBook;
                    db.updataRoom(2, exeRoom);
                    numRooms    = bookRoomsCB.getSelectedIndex()+1;
                    roomtype    = "Executive Room";
                }
            }
            else if (roomTypesCB.getSelectedIndex()== 2)
            {
                if (jSuite == 0)
                {
                    JOptionPane.showMessageDialog(null,"Sorry! No Junior Suite available.");
                }
                else
                {
                    jSuite -= roomBook;
                    db.updataRoom(3, jSuite);
                    numRooms    = bookRoomsCB.getSelectedIndex()+1;
                    roomtype    = "Junior Suite";
                }
            }
            else if (roomTypesCB.getSelectedIndex()== 3)
            {
                if (exeSuite == 0)
                {
                    JOptionPane.showMessageDialog(null,"Sorry! No Executive Suite available.");
                }
                else
                {
                    exeSuite -= roomBook;
                    db.updataRoom(4, exeSuite);
                    numRooms    = bookRoomsCB.getSelectedIndex()+1;
                    roomtype    = "Executive Suite";
                }
            }
            else if (roomTypesCB.getSelectedIndex()== 4)
            {
                if (pSuite == 0)
                {
                    JOptionPane.showMessageDialog(null,"Sorry! No Presidential Suite available.");
                }
                else
                {
                    pSuite -= roomBook;
                    db.updataRoom(5, pSuite);
                    numRooms    = bookRoomsCB.getSelectedIndex()+1;
                    roomtype    = "Presidential Suite";
                }
            }
            int totalStay = totalStayCB.getSelectedIndex()+1;
            query = "INSERT INTO UserRData ([Checkin],[Checkout],[Room Type],[No of Rooms],[No of Days]) VALUES (?,?,?,?,?)";
            ps = con.prepareStatement(query);
            ps.setString(1,cin);
            ps.setString(2,cout);
            ps.setString(3,roomtype);
            ps.setInt(4, numRooms);
            ps.setLong(5, totalStay);
            int results = ps.executeUpdate();
            
            query = "INSERT INTO Bill ([Rooms]) VALUES (?)";  
            ps = con.prepareStatement(query);
            ps.setInt(1,0);
            int r = ps.executeUpdate();            

            JOptionPane.showMessageDialog(null, "Your Room has been booked!","Booking Information", JOptionPane.INFORMATION_MESSAGE);
            
            Customers c     = new Customers(cin,cout,persons);
            this.setVisible(false);
            Reception res = new Reception ();
            res.setVisible(true);
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
                // TODO add your handling code here:
    }//GEN-LAST:event_bookBtnActionPerformed
   
    private void totalStayCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalStayCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalStayCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        AddGuest guest = new AddGuest ();
        guest.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void roomTypesCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypesCBActionPerformed
        if (roomTypesCB.getSelectedIndex()== 0)  
        {
            jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\quetta-serena-hotel.jpg"));
            jLabel6.setText("Welcome drink, Buffet breakfast, Mini-bar, Newspaper, Swimming pool,WiFi");
            jLabel5.setText("377 sq ft, 2 People,  $298");
        }
        else if (roomTypesCB.getSelectedIndex()== 1)  
        {
            jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\lw1878_94220256_720x450.jpg"));
            jLabel6.setText("All included from Deluxe package, Gym, Daily Fruits, Laundary, Meeting room");
            //jLabel6.setForeground(Color.red);
            jLabel5.setText("388 sq ft, 2 People,  $325");
        }
        else if (roomTypesCB.getSelectedIndex()== 2)  
        {
            jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\1481920857_Serena_Hotel_Islamabad_Suite_Executive.jpg"));
            jLabel6.setText("Same as Executive package");
            jLabel5.setText("581 sq ft, 2 People,  $375");
        }
        else if (roomTypesCB.getSelectedIndex()== 3)  
        {
            jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\nairobi-serena-hotel.jpg"));            
            jLabel6.setText("All included from Executive package, King bed, sitting room, Work desk");
            jLabel5.setText("646 sq ft, 2 People,  $498");
        }
        else if (roomTypesCB.getSelectedIndex()== 4)  
        {
            jLabel15.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\183063508.jpg"));            
            jLabel6.setText("All included from Executive Suite package, Dry cleaning, Pressing");
            jLabel5.setText("2120 sq ft, 2 People,  $2495");
        }

    }//GEN-LAST:event_roomTypesCBActionPerformed

    private void bookRoomsCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRoomsCBActionPerformed
        roomBook = bookRoomsCB.getSelectedIndex()+1;// TODO add your handling code here:
    }//GEN-LAST:event_bookRoomsCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookBtn;
    private javax.swing.JComboBox<String> bookRoomsCB;
    private com.toedter.calendar.JDateChooser checkinDC;
    private com.toedter.calendar.JDateChooser checkoutDC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> roomTypesCB;
    private javax.swing.JComboBox<String> totalStayCB;
    // End of variables declaration//GEN-END:variables

    private long daysBetween(Date din, Date dout) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
