/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPproject;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell4
 */
public class Services extends javax.swing.JFrame {

    /**
     * Creates new form Services
     */
    Connection          con     = null;
    PreparedStatement   ps      = null;
    ResultSet           rs      = null;
    String Email;
    int ID;
    String query;
    int food = 0;
    int beverages = 0;
    int laundary = 0;
    int cPT = 0;
    int cCB = 0;
    int cFF = 0;
    public Services() 
    {
        Email = JOptionPane.showInputDialog(null,"Enter your Email: ").trim().toLowerCase();
        try
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            
            query = "select * from UserPData where Email = ?";
            ps = con.prepareStatement(query);
            ps.setString(1,Email);
            rs = ps.executeQuery();
            
            int count = 0;
            
            while(rs.next())
            {
                ID = rs.getInt("ID");
                count=count+1;
            }
            if (count == 1)
            {
                initComponents();
        }
            else if (count > 1)
            {
                JOptionPane.showMessageDialog(null, "Duplicate User found, Access Deined!");
                this.setVisible(false);
                Account acc = new Account ();
                acc.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Entry!");      
                this.setVisible(false);
                Account acc = new Account ();
                acc.setVisible(true);
            }
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        doneBtn = new javax.swing.JButton();
        menuBtn = new javax.swing.JButton();
        Laundary = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        meal2CB = new javax.swing.JCheckBox();
        meal1CB = new javax.swing.JCheckBox();
        meal3CB = new javax.swing.JCheckBox();
        iceShakeCB = new javax.swing.JCheckBox();
        coldDrinkCB = new javax.swing.JCheckBox();
        milkShakeCB = new javax.swing.JCheckBox();
        freshJuiceCB = new javax.swing.JCheckBox();
        blackCoffeeCB = new javax.swing.JCheckBox();
        greenTeaCB = new javax.swing.JCheckBox();
        teaCB = new javax.swing.JCheckBox();
        cappuccinoCB = new javax.swing.JCheckBox();
        lassiCB = new javax.swing.JCheckBox();
        coldCoffeeCB = new javax.swing.JCheckBox();
        mintCB = new javax.swing.JCheckBox();
        limeCB = new javax.swing.JCheckBox();
        washCB = new javax.swing.JCheckBox();
        dryCleanCB = new javax.swing.JCheckBox();
        pressCB = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 600));
        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 540, 55, 21);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(480, 0, 100, 130);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to Serena Hotel");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 10, 330, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\serena-hotels-black.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 100, 130);

        doneBtn.setBackground(new java.awt.Color(0, 0, 0));
        doneBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        doneBtn.setForeground(new java.awt.Color(255, 255, 255));
        doneBtn.setText("Done");
        doneBtn.setToolTipText("");
        doneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneBtnActionPerformed(evt);
            }
        });
        jPanel2.add(doneBtn);
        doneBtn.setBounds(230, 500, 150, 30);

        menuBtn.setBackground(new java.awt.Color(0, 0, 0));
        menuBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuBtn.setForeground(new java.awt.Color(255, 255, 255));
        menuBtn.setText("Food Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });
        jPanel2.add(menuBtn);
        menuBtn.setBounds(230, 150, 150, 30);

        Laundary.setBackground(new java.awt.Color(0, 0, 0));
        Laundary.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        Laundary.setForeground(new java.awt.Color(255, 255, 255));
        Laundary.setText("Laundary");
        Laundary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaundaryActionPerformed(evt);
            }
        });
        jPanel2.add(Laundary);
        Laundary.setBounds(230, 400, 150, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Extra Meal");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 190, 80, 17);

        meal2CB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        meal2CB.setText("Chinese Bowl");
        meal2CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal2CBActionPerformed(evt);
            }
        });
        jPanel2.add(meal2CB);
        meal2CB.setBounds(260, 210, 110, 20);

        meal1CB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        meal1CB.setText("Pakistani Thali");
        meal1CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal1CBActionPerformed(evt);
            }
        });
        jPanel2.add(meal1CB);
        meal1CB.setBounds(110, 210, 110, 21);

        meal3CB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        meal3CB.setText("Fast Food");
        meal3CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal3CBActionPerformed(evt);
            }
        });
        jPanel2.add(meal3CB);
        meal3CB.setBounds(410, 210, 130, 20);

        iceShakeCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        iceShakeCB.setText("Icecream Shakes");
        iceShakeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iceShakeCBActionPerformed(evt);
            }
        });
        jPanel2.add(iceShakeCB);
        iceShakeCB.setBounds(410, 260, 130, 20);

        coldDrinkCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        coldDrinkCB.setText("Cold Drink");
        coldDrinkCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldDrinkCBActionPerformed(evt);
            }
        });
        jPanel2.add(coldDrinkCB);
        coldDrinkCB.setBounds(410, 290, 110, 20);

        milkShakeCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        milkShakeCB.setText("Milk Shake");
        milkShakeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkShakeCBActionPerformed(evt);
            }
        });
        jPanel2.add(milkShakeCB);
        milkShakeCB.setBounds(410, 320, 110, 20);

        freshJuiceCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        freshJuiceCB.setText("Fresh Juice");
        freshJuiceCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freshJuiceCBActionPerformed(evt);
            }
        });
        jPanel2.add(freshJuiceCB);
        freshJuiceCB.setBounds(410, 350, 110, 20);

        blackCoffeeCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        blackCoffeeCB.setText("Black Coffee");
        blackCoffeeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackCoffeeCBActionPerformed(evt);
            }
        });
        jPanel2.add(blackCoffeeCB);
        blackCoffeeCB.setBounds(260, 350, 110, 20);

        greenTeaCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        greenTeaCB.setText("Green Tea");
        greenTeaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenTeaCBActionPerformed(evt);
            }
        });
        jPanel2.add(greenTeaCB);
        greenTeaCB.setBounds(260, 260, 110, 20);

        teaCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        teaCB.setText("Tea");
        teaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaCBActionPerformed(evt);
            }
        });
        jPanel2.add(teaCB);
        teaCB.setBounds(260, 290, 110, 20);

        cappuccinoCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        cappuccinoCB.setText("Cappuccino");
        cappuccinoCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappuccinoCBActionPerformed(evt);
            }
        });
        jPanel2.add(cappuccinoCB);
        cappuccinoCB.setBounds(260, 320, 110, 20);

        lassiCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lassiCB.setText("Lassi");
        lassiCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lassiCBActionPerformed(evt);
            }
        });
        jPanel2.add(lassiCB);
        lassiCB.setBounds(110, 350, 110, 21);

        coldCoffeeCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        coldCoffeeCB.setText("Cold Coffee");
        coldCoffeeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldCoffeeCBActionPerformed(evt);
            }
        });
        jPanel2.add(coldCoffeeCB);
        coldCoffeeCB.setBounds(110, 320, 110, 21);

        mintCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        mintCB.setForeground(new java.awt.Color(255, 255, 255));
        mintCB.setText("Mint Margarita");
        mintCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mintCBActionPerformed(evt);
            }
        });
        jPanel2.add(mintCB);
        mintCB.setBounds(110, 290, 110, 21);

        limeCB.setBackground(new java.awt.Color(255, 255, 255));
        limeCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        limeCB.setText("Lime Lemonade");
        limeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limeCBActionPerformed(evt);
            }
        });
        jPanel2.add(limeCB);
        limeCB.setBounds(110, 260, 110, 21);

        washCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        washCB.setForeground(new java.awt.Color(255, 255, 255));
        washCB.setText("Wash");
        washCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washCBActionPerformed(evt);
            }
        });
        jPanel2.add(washCB);
        washCB.setBounds(110, 440, 110, 21);

        dryCleanCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        dryCleanCB.setForeground(new java.awt.Color(255, 255, 255));
        dryCleanCB.setText("Dry Clean");
        dryCleanCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryCleanCBActionPerformed(evt);
            }
        });
        jPanel2.add(dryCleanCB);
        dryCleanCB.setBounds(260, 440, 110, 20);

        pressCB.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        pressCB.setForeground(new java.awt.Color(255, 255, 255));
        pressCB.setText("Press");
        pressCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressCBActionPerformed(evt);
            }
        });
        jPanel2.add(pressCB);
        pressCB.setBounds(410, 440, 110, 20);

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Services");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(230, 90, 150, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Beverages");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(270, 240, 70, 17);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\OOP Project\\photo-1414235077428-338989a2e8c0.jpg")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, -60, 710, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        Account a  = new Account ();
        a.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void limeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limeCBActionPerformed

    private void LaundaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaundaryActionPerformed
        JOptionPane.showMessageDialog(null,"***Laundary Servies***\n\n1) Wash - $3/piece\n2) Dry Clean - $10/piece\n3) Press - &5/piece","Laundary Services",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LaundaryActionPerformed

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        JOptionPane.showMessageDialog(null, "***Extra Meal***\n\n1) Pakistani Thali - $20\n2) Chinese Bowl - $15\n3) Fast Food - $25\n\n***Beverages***\n\n1)Lime Lemonade - $5\n2) MintMargrita - $15\n3) Cold Coffee - $10\n4) Lassi - $10\n5) Green Tea - $7\n6) Tea - $5\n7) Cuppaccino - 15\n8) Black Coffee - $15\n9) Icecream Shake - $20\n10) Cold Drink - $5\n11) Milk Shake - $20\n12) Fresh Juice - $15","Food Menu",JOptionPane.PLAIN_MESSAGE);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBtnActionPerformed

    private void doneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneBtnActionPerformed
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            query = "select * from Bill where ID = ?";
            ps = con.prepareStatement(query);
            ps.setInt(1,ID);
            rs = ps.executeQuery();
            while (rs.next())
            {
                food = rs.getInt("Food");
                beverages = rs.getInt("Beverages");
                laundary = rs.getInt("Laundary");
            }
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            query = "select * from CheckFood";
            ps = con.prepareStatement(query);
            rs = ps.executeQuery();
            while (rs.next())
            {
                cPT = rs.getInt("Pakistani Thali");
                cCB = rs.getInt("Chinese Bowl");
                cFF = rs.getInt("Fast Food");
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(Services.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(cPT);
        if (cPT > 0)
        {
            if(meal1CB.isSelected())
            {
                cPT-=1;
                food+=20;
            }
        }
        else
        {
            meal1CB.setEnabled(false);
        }
        if (cCB > 0)
            if(meal2CB.isSelected())
            {
                cCB-=1;
                food+=15;
            }
        else
        {
            meal2CB.setEnabled(false);
        }
        if (cFF > 0)
            if(meal3CB.isSelected())
            {
                cFF-=1;
                food+=25;
            }
        else
        {
            meal3CB.setEnabled(false);
        }
            
            
        if(limeCB.isSelected())
        {
            beverages+=5;
        }
        if(mintCB.isSelected())
        {
            beverages+=15;
        }
        if(coldCoffeeCB.isSelected())
        {
            beverages+=10;
        }
        if(lassiCB.isSelected())
        {
            beverages+=10;
        }
        if(greenTeaCB.isSelected())
        {
            beverages+=7;
        }
        if(teaCB.isSelected())
        {
            beverages+=5;
        }
        if(cappuccinoCB.isSelected())
        {
            beverages+=15;
        }
        if(blackCoffeeCB.isSelected())
        {
            beverages+=15;
        }
        if(iceShakeCB.isSelected())
        {
            beverages+=20;
        }
        if(coldDrinkCB.isSelected())
        {
            beverages+=5;
        }
        if(milkShakeCB.isSelected())
        {
            beverages+=20;
        }
        if(freshJuiceCB.isSelected())
        {
            beverages+=15;
        }
        if(washCB.isSelected())
        {
            laundary+=3;
        }
        if(dryCleanCB.isSelected())
        {
            laundary+=10;
        }
        if(pressCB.isSelected())
        {
            laundary+=5;
        }
        try 
        {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            query = "Update Bill set Food = ?, Beverages = ?, Laundary = ? WHERE ID = ?";
            ps = con.prepareStatement(query);
            ps.setInt(1, food);
            ps.setInt(2, beverages);
            ps.setInt(3, laundary);
            ps.setInt(4, ID);
            int doneUpdate = ps.executeUpdate();
            
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            con = DriverManager.getConnection("jdbc:ucanaccess://D:\\OOP Project\\Project\\Mydb.accdb");
            query = "Update CheckFood set [Pakistani Thali] = ?, [Chinese Bowl] = ?, [Fast Food] = ?";
            ps = con.prepareStatement(query);
            ps.setInt(1, cPT);
            ps.setInt(2, cCB);
            ps.setInt(3, cFF);
            int doneUpdate1 = ps.executeUpdate();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Services.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_doneBtnActionPerformed

    private void mintCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mintCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mintCBActionPerformed

    private void coldCoffeeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldCoffeeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldCoffeeCBActionPerformed

    private void lassiCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lassiCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lassiCBActionPerformed

    private void blackCoffeeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackCoffeeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blackCoffeeCBActionPerformed

    private void greenTeaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenTeaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenTeaCBActionPerformed

    private void teaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaCBActionPerformed

    private void cappuccinoCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappuccinoCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cappuccinoCBActionPerformed

    private void iceShakeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iceShakeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iceShakeCBActionPerformed

    private void coldDrinkCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldDrinkCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldDrinkCBActionPerformed

    private void milkShakeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkShakeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_milkShakeCBActionPerformed

    private void freshJuiceCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freshJuiceCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_freshJuiceCBActionPerformed

    private void meal2CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal2CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal2CBActionPerformed

    private void meal1CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal1CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal1CBActionPerformed

    private void meal3CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal3CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meal3CBActionPerformed

    private void washCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washCBActionPerformed

    private void dryCleanCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryCleanCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryCleanCBActionPerformed

    private void pressCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pressCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Laundary;
    private javax.swing.JCheckBox blackCoffeeCB;
    private javax.swing.JCheckBox cappuccinoCB;
    private javax.swing.JCheckBox coldCoffeeCB;
    private javax.swing.JCheckBox coldDrinkCB;
    private javax.swing.JButton doneBtn;
    private javax.swing.JCheckBox dryCleanCB;
    private javax.swing.JCheckBox freshJuiceCB;
    private javax.swing.JCheckBox greenTeaCB;
    private javax.swing.JCheckBox iceShakeCB;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox lassiCB;
    private javax.swing.JCheckBox limeCB;
    private javax.swing.JCheckBox meal1CB;
    private javax.swing.JCheckBox meal2CB;
    private javax.swing.JCheckBox meal3CB;
    private javax.swing.JButton menuBtn;
    private javax.swing.JCheckBox milkShakeCB;
    private javax.swing.JCheckBox mintCB;
    private javax.swing.JCheckBox pressCB;
    private javax.swing.JCheckBox teaCB;
    private javax.swing.JCheckBox washCB;
    // End of variables declaration//GEN-END:variables
}
